# Generated by Django 4.0.2 on 2022-05-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='empresa',
            field=models.CharField(choices=[('Natura', 'Natura'), ('Millanel', 'Millanel'), ('Tupper', 'Tupper'), ('Winnem', 'Winnem'), ('Avon', 'Avon'), ('MeryKay', 'MeryKay')], default='Natura', max_length=8),
        ),
    ]
